
-- ==========================================
-- REPARACIÓN JX4 - COLUMNAS Y CACHÉ
-- ==========================================

-- 1. Asegurar columna 'metodo' en pedidos (causante del error PGRST204)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='metodo') THEN
        ALTER TABLE orders ADD COLUMN metodo TEXT DEFAULT 'retiro';
    END IF;
END $$;

-- 2. Asegurar que la tabla de empleos exista
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  requisitos TEXT,
  activo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Asegurar que admin_users exista (para el login)
CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Deshabilitar RLS para facilitar la gestión inicial
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE site_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;

-- 5. CRITICO: Recargar el esquema para que Supabase reconozca la nueva columna 'metodo'
NOTIFY pgrst, 'reload schema';
